name: OVC
on:
  merge_group:
  push:
    branches:
      - 'master'
      - 'releases/**'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  Pylint-UT:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone OpenVINO
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Setup Python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@3624ceb22c1c5a301c8db4169662070a689d9ea8 # v4.1.1
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('src/bindings/python/requirements*.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
            ${{ runner.os }}-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools
          # For UT
          pip install unittest-xml-reporting==3.0.2
          pip install pylint>=2.7.0
          pip install pyenchant>=3.0.0

          pip install -r requirements.txt
        working-directory: src/bindings/python/

      - name: Pylint-OVC
        run: pylint -d C,R,W openvino/tools/ovc
        working-directory: tools/ovc

  Overall_Status:
    name: ci/gha_overall_status_ovc
    needs: [Pylint-UT]
    if: ${{ always() }}
    runs-on: ubuntu-latest
    steps:
      - name: Check status of all jobs
        if: >-
          ${{
            contains(needs.*.result, 'failure') ||
            contains(needs.*.result, 'cancelled')
          }}
        run: exit 1
